import {
  Activity,
  Airplay,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Anchor,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  Banknote,
  BarChart,
  BarChart2,
  Battery,
  BatteryCharging,
  Bell,
  Bike,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  BookOpen,
  Box,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  Clipboard,
  Clock,
  Cloud,
  CloudCog,
  CloudRain,
  CloudSun,
  Code,
  Code2,
  Coffee,
  Cog,
  Coins,
  Columns,
  Compass,
  Copy,
  CreditCard,
  Crop,
  Crown,
  Database,
  Diamond,
  Disc,
  DollarSign,
  Download,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FastForward,
  Feather,
  File,
  FileArchive,
  FileAudio,
  FileCode,
  FileImage,
  FilePlus,
  FileText,
  FileVideo,
  Film,
  Filter,
  Flag,
  Flame,
  FlipHorizontal,
  FlipVertical,
  Flower,
  Folder,
  FolderCheck,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FolderX,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitCommit,
  Github,
  GitMerge,
  GitPullRequest,
  Globe,
  GraduationCap,
  Grid,
  Grip,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Highlighter,
  History,
  Home,
  Hourglass,
  Image,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Keyboard,
  Laptop,
  Layers,
  Layout,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Link,
  Link2,
  Linkedin,
  List,
  ListChecks,
  ListOrdered,
  Loader,
  Lock,
  type LucideIcon,
  Mail,
  Map as MapIcon,
  MapPin,
  Maximize,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Mouse,
  Move,
  Music,
  Navigation,
  Navigation2,
  Network,
  Newspaper,
  Octagon,
  Package,
  Palette,
  Paperclip,
  Pause,
  Pen,
  Pencil,
  Phone,
  PhoneCall,
  PieChart,
  Pin,
  Plane,
  Play,
  PlayCircle,
  Plug,
  Plus,
  PlusCircle,
  Podcast,
  Pointer,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Radio,
  Redo,
  RefreshCw,
  Repeat,
  Reply,
  Rewind,
  Rocket,
  RotateCcw,
  RotateCw,
  Rss,
  Ruler,
  Save,
  Scale,
  Scan,
  ScanFace,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  Signal,
  SkipBack,
  SkipForward,
  Slack,
  Smartphone,
  Smile,
  Sparkles,
  Speaker,
  Square,
  Star,
  StopCircle,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tag,
  Tags,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToggleLeft,
  ToggleRight,
  Train,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Undo,
  Unlink,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  Voicemail,
  Volume2,
  Wallet,
  Wand2,
  Watch,
  Wifi,
  Wind,
  Wrench,
  X,
  XCircle,
  Youtube,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

// Map of icon keys to their lucide-react components
export const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  airplay: Airplay,
  "alarm-clock": AlarmClock,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "align-center": AlignCenter,
  "align-left": AlignLeft,
  "align-right": AlignRight,
  anchor: Anchor,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "at-sign": AtSign,
  award: Award,
  banknote: Banknote,
  "bar-chart": BarChart,
  "bar-chart-2": BarChart2,
  battery: Battery,
  "battery-charging": BatteryCharging,
  bell: Bell,
  bike: Bike,
  bluetooth: Bluetooth,
  bold: Bold,
  book: Book,
  "book-open": BookOpen,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  bug: Bug,
  building: Building,
  "building-2": Building2,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle-2": CheckCircle2,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-dot": CircleDot,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  code: Code,
  "code-2": Code2,
  coffee: Coffee,
  cog: Cog,
  coins: Coins,
  columns: Columns,
  compass: Compass,
  copy: Copy,
  "credit-card": CreditCard,
  crop: Crop,
  crown: Crown,
  database: Database,
  diamond: Diamond,
  disc: Disc,
  "dollar-sign": DollarSign,
  download: Download,
  droplet: Droplet,
  edit: Edit,
  "edit-2": Edit2,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  facebook: Facebook,
  "fast-forward": FastForward,
  feather: Feather,
  file: File,
  "file-archive": FileArchive,
  "file-audio": FileAudio,
  "file-code": FileCode,
  "file-image": FileImage,
  "file-plus": FilePlus,
  "file-text": FileText,
  "file-video": FileVideo,
  film: Film,
  filter: Filter,
  flag: Flag,
  flame: Flame,
  "flip-horizontal": FlipHorizontal,
  "flip-vertical": FlipVertical,
  flower: Flower,
  folder: Folder,
  "folder-check": FolderCheck,
  "folder-minus": FolderMinus,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "folder-x": FolderX,
  "gamepad-2": Gamepad2,
  gauge: Gauge,
  gem: Gem,
  gift: Gift,
  github: Github,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "graduation-cap": GraduationCap,
  grid: Grid,
  grip: Grip,
  "hard-drive": HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  "help-circle": HelpCircle,
  hexagon: Hexagon,
  highlighter: Highlighter,
  history: History,
  home: Home,
  hourglass: Hourglass,
  image: Image,
  inbox: Inbox,
  info: Info,
  instagram: Instagram,
  italic: Italic,
  key: Key,
  keyboard: Keyboard,
  laptop: Laptop,
  layers: Layers,
  layout: Layout,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  "link-2": Link2,
  linkedin: Linkedin,
  list: List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  loader: Loader,
  lock: Lock,
  mail: Mail,
  map: MapIcon,
  "map-pin": MapPin,
  maximize: Maximize,
  medal: Medal,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  minimize: Minimize,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  mountain: Mountain,
  mouse: Mouse,
  move: Move,
  music: Music,
  navigation: Navigation,
  "navigation-2": Navigation2,
  network: Network,
  newspaper: Newspaper,
  octagon: Octagon,
  package: Package,
  palette: Palette,
  paperclip: Paperclip,
  pause: Pause,
  pen: Pen,
  pencil: Pencil,
  phone: Phone,
  "phone-call": PhoneCall,
  "pie-chart": PieChart,
  pin: Pin,
  plane: Plane,
  play: Play,
  "play-circle": PlayCircle,
  plug: Plug,
  plus: Plus,
  "plus-circle": PlusCircle,
  podcast: Podcast,
  pointer: Pointer,
  power: Power,
  printer: Printer,
  puzzle: Puzzle,
  "qr-code": QrCode,
  quote: Quote,
  radio: Radio,
  redo: Redo,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  reply: Reply,
  rewind: Rewind,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  rss: Rss,
  ruler: Ruler,
  save: Save,
  scale: Scale,
  scan: Scan,
  "scan-face": ScanFace,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  share: Share,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  ship: Ship,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  signal: Signal,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  slack: Slack,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  speaker: Speaker,
  square: Square,
  star: Star,
  "stop-circle": StopCircle,
  store: Store,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  table: Table,
  tablet: Tablet,
  tag: Tag,
  tags: Tags,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  train: Train,
  trash: Trash,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  twitter: Twitter,
  type: Type,
  umbrella: Umbrella,
  underline: Underline,
  undo: Undo,
  unlink: Unlink,
  unlock: Unlock,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  users: Users,
  "user-x": UserX,
  video: Video,
  voicemail: Voicemail,
  "volume-2": Volume2,
  wallet: Wallet,
  "wand-2": Wand2,
  watch: Watch,
  wifi: Wifi,
  wind: Wind,
  wrench: Wrench,
  x: X,
  "x-circle": XCircle,
  youtube: Youtube,
  zap: Zap,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
};

// All available icon keys for the icon picker (sorted alphabetically)
export const iconKeys = Object.keys(iconMap).sort();

// Get icon component by key, with optional fallback
export function getIcon(
  key: string | undefined,
  fallback?: LucideIcon
): LucideIcon | undefined {
  if (!key) {
    return fallback;
  }
  return iconMap[key] || fallback;
}

// Default icons for node types
export const defaultNodeIcons: Record<string, string> = {
  milestone: "flag",
  goal: "target",
  task: "check-circle-2",
};

// Get icon for a node based on its stored icon or type
export function getNodeIcon(
  iconKey: string | undefined,
  nodeType: string
): LucideIcon {
  if (iconKey && iconMap[iconKey]) {
    return iconMap[iconKey];
  }
  const defaultKey = defaultNodeIcons[nodeType] || "circle";
  return iconMap[defaultKey] || Circle;
}

// Popular/commonly used icons (for featured section in picker)
export const popularIconKeys = [
  "target",
  "flag",
  "check-circle-2",
  "star",
  "heart",
  "bookmark",
  "folder",
  "file",
  "calendar",
  "clock",
  "bell",
  "user",
  "users",
  "home",
  "settings",
  "search",
  "mail",
  "message-circle",
  "phone",
  "globe",
  "map-pin",
  "navigation",
  "compass",
  "rocket",
  "zap",
  "flame",
  "sun",
  "moon",
  "cloud",
  "coffee",
  "book",
  "graduation-cap",
  "briefcase",
  "building",
  "store",
  "shopping-cart",
  "credit-card",
  "wallet",
  "dollar-sign",
  "trending-up",
  "bar-chart",
  "pie-chart",
  "activity",
  "heart-pulse",
  "lightbulb",
  "puzzle",
  "gamepad-2",
  "music",
  "video",
  "camera",
  "image",
  "palette",
  "pen",
  "pencil",
  "highlighter",
  "code",
  "terminal",
  "database",
  "server",
  "cloud-cog",
  "git-branch",
  "github",
  "package",
  "box",
  "archive",
  "trash-2",
  "download",
  "upload",
  "share-2",
  "link",
  "external-link",
  "lock",
  "unlock",
  "key",
  "shield",
  "shield-check",
  "award",
  "trophy",
  "medal",
  "crown",
  "diamond",
  "gem",
  "gift",
  "smile",
  "thumbs-up",
  "thumbs-down",
  "move",
  "maximize",
  "minimize",
  "plus",
  "minus",
  "x",
  "check",
  "alert-circle",
  "alert-triangle",
  "info",
  "help-circle",
  "circle",
  "square",
  "triangle",
  "hexagon",
  "octagon",
  "sparkles",
  "wand-2",
];
